// src/App.jsx
import { useState, useEffect, useRef } from "react";
import {
  Alert,
  Container,
  Typography,
  Button,
  Select,
  MenuItem,
  InputLabel,
  FormControl,
  Slider,
  LinearProgress,
  Box,
  Link,
  List,
  ListItem,
  ListItemText,
  IconButton,
} from "@mui/material";

import { MuiFileInput } from "mui-file-input";
import NewspaperIcon from "@mui/icons-material/Newspaper";
import DeleteIcon from "@mui/icons-material/Delete";

import GitHubIcon from "@mui/icons-material/GitHub";

import { PredictionsTable } from "./PredictionsTable";
import { PredictionsPlot } from "./PredictionsPlot";

import SIMSWorker from "./worker?worker";

function App() {
  const [modelInfoList, setModelInfoList] = useState([]);
  const [selectedModel, setSelectedModel] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [cellRangePercent, setCellRangePercent] = useState(25);
  const [statusMessage, setStatusMessage] = useState("");
  const [progress, setProgress] = useState(0);
  const [isPredicting, setIsPredicting] = useState(false);
  const [topGenes, setTopGenes] = useState([]);
  const [predictions, setPredictions] = useState(null);
  const [workerInstance, setWorkerInstance] = useState(null);
  const [dbDatasets, setDbDatasets] = useState([]);

  const resultsRef = useRef(null);

  const sitePath =
    window.location.origin +
    window.location.pathname.slice(
      0,
      window.location.pathname.lastIndexOf("/")
    );

  // On mount, load models list
  useEffect(() => {
    fetchModels();
    fetchSampleFile();
    loadDatasets();
  }, []);

  // Load datasets from IndexedDB
  async function loadDatasets() {
    const request = indexedDB.open("sims-web", 1);
    request.onupgradeneeded = (event) => {
      console.log("Creating results database");
      const db = event.target.result;
      db.createObjectStore("datasets", { keyPath: "datasetLabel" });
    };
    request.onsuccess = () => {
      const db = request.result;
      if (db.objectStoreNames.contains("datasets")) {
        const tx = db.transaction("datasets", "readonly");
        const store = tx.objectStore("datasets");
        const getAllRequest = store.getAll();
        getAllRequest.onsuccess = () => {
          const result = getAllRequest.result || [];
          setDbDatasets(result);
          db.close();
        };
      } else {
        console.log("No existing results found");
      }
    };
  }

  // Delete a dataset
  function handleDeleteDataset(label) {
    console.log("Deleting results", label);
    const request = indexedDB.open("sims-web", 1);
    request.onsuccess = () => {
      const db = request.result;
      const tx = db.transaction("datasets", "readwrite");
      const store = tx.objectStore("datasets");
      store.delete(label);
      tx.oncomplete = () => {
        db.close();
        loadDatasets();
      };
    };
  }

  // Fill in a sample file so a user can just hit predict to try out
  async function fetchSampleFile() {
    try {
      const sampleFileName = "sample.h5ad";
      // const sampleFileName = "sample-sparse.h5ad";
      const response = await fetch(sampleFileName);
      const blob = await response.blob();
      const file = new File([blob], sampleFileName, { type: blob.type });
      setSelectedFile(file);
      console.log("Sample File:", file);
    } catch (error) {
      console.error("Error:", error);
    }
  }

  async function fetchModels() {
    try {
      const resp = await fetch("models/models.txt");
      const text = await resp.text();
      const modelIDs = text.split("\n").filter((id) => id.trim() !== "");
      const modelDescriptions = [];
      for (const mid of modelIDs) {
        try {
          const r = await fetch(`models/${mid}.json`);
          if (!r.ok) {
            throw new Error(`Failed to fetch ${mid}.json`);
          }
          const desc = await r.json();
          desc.id = mid;
          modelDescriptions.push(desc);
        } catch (e) {
          console.error(e);
        }
      }
      setModelInfoList(modelDescriptions);
      setSelectedModel("default");
    } catch (err) {
      console.error("Failed fetching model list:", err);
    }
  }

  useEffect(() => {
    const worker = new SIMSWorker();
    setWorkerInstance(worker);

    worker.onmessage = (evt) => {
      switch (evt.data.type) {
        case "status":
          setStatusMessage(evt.data.message);
          break;
        case "progress":
          setStatusMessage(evt.data.message);
          setProgress(
            Math.round((evt.data.countFinished / evt.data.totalToProcess) * 100)
          );
          break;
        case "predictions":
          setPredictions(evt.data);
          setStatusMessage(
            `Processed ${evt.data.totalProcessed} of ${
              evt.data.totalNumCells
            } cells in ${evt.data.elapsedTime?.toFixed(2)} minutes`
          );
          setTopGenes(
            evt.data.overallTopGenes.map((item) => evt.data.genes[item])
          );
          setIsPredicting(false);
          loadDatasets(); // Refresh the list of stored datasets
          break;
        case "error":
          setStatusMessage(evt.data.error.toString());
          setIsPredicting(false);
          break;
        default:
          break;
      }

      return () => {
        // Cleanup
        worker.terminate();
      };
    };
  }, []);

  // Start prediction
  async function handlePredict() {
    if (!workerInstance) return;
    // Clear existing output
    setProgress(0);
    setTopGenes([]);
    setPredictions(null);
    if (!selectedModel || !selectedFile) {
      setStatusMessage("Please select a model and file.");
      return;
    }
    setIsPredicting(true);
    setStatusMessage("Starting prediction...");
    workerInstance.postMessage({
      type: "startPrediction",
      modelURL: `${sitePath}/models`,
      modelID: selectedModel,
      h5File: selectedFile,
      cellRangePercent,
    });
  }

  // Stop prediction
  function handleStop() {
    if (workerInstance) {
      workerInstance.terminate();
      setWorkerInstance(null);
    }
    setStatusMessage("Prediction stopped.");
    setIsPredicting(false);
    setProgress(0);
  }

  // Render
  return (
    <Container maxWidth="lg" sx={{ my: 4 }}>
      <Box display="flex" justifyContent="space-between" alignItems="center">
        <Typography variant="h4">SIMS Web</Typography>
        <Box>
          <Link
            href="https://www.cell.com/cell-genomics/abstract/S2666-979X(24)00165-4"
            target="_blank"
            underline="none"
            sx={{ mr: 2 }}
          >
            <NewspaperIcon />
          </Link>
          <Link
            href="https://github.com/braingeneers/sims-web"
            target="_blank"
            underline="none"
          >
            <GitHubIcon />
          </Link>
        </Box>
      </Box>

      <Box mt={3} mb={3}>
        {/* Model Selection */}
        <FormControl fullWidth margin="normal">
          <InputLabel id="model-label">Select a model</InputLabel>
          <Select
            labelId="model-label"
            label="Select a model"
            value={selectedModel}
            onChange={(e) => setSelectedModel(e.target.value)}
          >
            {modelInfoList.map((m) => (
              <MenuItem key={m.id} value={m.id}>
                {m.title}, {m.submitter}
              </MenuItem>
            ))}
          </Select>
        </FormControl>

        <MuiFileInput
          fullWidth
          placeholder="Select an AnnData/Scanpy (.h5ad) file"
          value={selectedFile}
          onChange={setSelectedFile}
          inputProps={{ accept: ".h5ad" }}
        />

        {/* Slider */}
        <Box mt={2}>
          <Typography>% Of Cells To Process: {cellRangePercent}%</Typography>
          <Slider
            min={0}
            max={100}
            step={1}
            value={cellRangePercent}
            onChange={(e, val) => setCellRangePercent(val)}
            valueLabelDisplay="auto"
          />
        </Box>

        <Box mt={2}>
          <Button
            variant="contained"
            onClick={handlePredict}
            disabled={isPredicting}
          >
            Predict
          </Button>
          <Button
            variant="contained"
            color="error"
            onClick={handleStop}
            sx={{ ml: 2 }}
          >
            Stop
          </Button>
        </Box>
      </Box>

      <Typography variant="h5" sx={{ mt: 4 }}>
        Results
      </Typography>
      <List dense>
        {dbDatasets.map((ds) => (
          <ListItem key={ds.datasetLabel}>
            <ListItemText
              primary={`${ds.datasetLabel} (model: ${ds.modelID})`}
            />
            <IconButton onClick={() => handleDeleteDataset(ds.datasetLabel)}>
              <DeleteIcon />
            </IconButton>
          </ListItem>
        ))}
      </List>

      {/* Status and Progress */}
      <Typography>{statusMessage}</Typography>
      {isPredicting && (
        <Box my={2}>
          <LinearProgress variant="determinate" value={progress} />
          <Typography>{progress}%</Typography>
        </Box>
      )}

      {!window.crossOriginIsolated && (
        <Alert severity="warning" sx={{ mt: 2 }}>
          Unable to use multiple cpu cores - notify the site owner
        </Alert>
      )}

      {/* Layout for top genes + scatter plot */}
      <Box display="flex" mt={4}>
        <Box width="25%" mr={4}>
          <Typography variant="h6">
            {topGenes.length ? "Top 10 Genes" : ""}
          </Typography>
          <List dense>
            {topGenes.map((gene) => (
              <ListItem key={gene}>
                <ListItemText primary={`${gene}`} />
              </ListItem>
            ))}
          </List>
        </Box>
        <PredictionsPlot width={450} height={450} predictions={predictions} />
      </Box>

      {/* Container for table or results */}
      <Box ref={resultsRef} mt={4}></Box>
      <PredictionsTable predictions={predictions} />
    </Container>
  );
}

export default App;

// src/App.vue
<template>
  <v-app>
    <v-app-bar>
      <v-toolbar-title>SIMS Web</v-toolbar-title>

      <!-- File Selector -->
      <v-file-input
        v-model="selectedFile"
        accept=".h5ad"
        variant="underlined"
        style="max-width: 25%"
        prepend-icon="mdi-dna"
        hint="You must select a .h5ad file"
        @update:model-value="handleFileSelected"
      >
        <template v-if="selectedFile" #selection>
          {{
            selectedFile.name.length > 30
              ? selectedFile.name.slice(0, 25) + '...'
              : selectedFile.name
          }}</template
        ></v-file-input
      >

      <!-- Labeling Background Dataset-->
      <v-select
        v-model="selectedPredictWorker"
        :items="predictWorkerOptions"
        variant="underlined"
        style="max-width: 25%"
        prepend-icon="mdi-label-multiple"
        item-title="title"
        item-value="value"
      ></v-select>

      <!-- Second Worker Selector -->
      <v-select
        v-model="selectedClusterWorker"
        :items="clusterWorkerOptions"
        prepend-icon="mdi-scatter-plot"
        variant="underlined"
        style="max-width: 25%"
      ></v-select>

      <!-- Run Button -->
      <v-app-bar-nav-icon
        color="primary"
        @click="runPipeline"
        :loading="isProcessing"
        icon="mdi-play"
      >
      </v-app-bar-nav-icon>

      <!-- Stop Button -->
      <v-app-bar-nav-icon color="error" @click="handleStop" icon="mdi-stop"></v-app-bar-nav-icon>
      <v-app-bar-nav-icon @click="toggleTheme">
        <v-icon>mdi-theme-light-dark</v-icon>
      </v-app-bar-nav-icon>
    </v-app-bar>

    <v-main>
      <v-container fluid>
        <!-- Status Display -->
        <v-card class="mb-4">
          <v-card-text>
            <v-progress-linear
              v-if="isProcessing"
              :model-value="processingProgress"
              color="primary"
              height="10"
            ></v-progress-linear>
            <p v-if="currentStatus">{{ currentStatus }}</p>
          </v-card-text>
        </v-card>

        <!-- File Information Display -->
        <v-card v-if="resultsDB" class="mb-4">
          <v-card-title>{{ resultsDB.datasetLabel }}</v-card-title>
          <v-card-text>
            <strong>Cells:</strong> {{ resultsDB.cellNames.length }} <strong>Genes:</strong>
            {{ resultsDB.genes.length }}
          </v-card-text>
        </v-card>

        <!-- Predictions Plot -->
        <v-card v-if="resultsDB" class="mb-4">
          <v-card-title>UMAP</v-card-title>
          <v-card-text>
            <predictions-plot
              :width="450"
              :height="450"
              :labels="resultsDB.cellTypes"
              :coordinates="resultsDB.coords"
            ></predictions-plot>
          </v-card-text>
        </v-card>

        <!-- Predictions Sankey -->
        <v-card v-if="resultsDB" class="mb-4">
          <v-card-title>Gene's Driving Labels</v-card-title>
          <v-card-text>
            <predictions-sankey
              :cell-types="resultsDB.cellTypes"
              :cell-type-names="resultsDB.cellTypeNames"
              :top-gene-indices-by-class="resultsDB.topGeneIndicesByClass"
              :genes="resultsDB.genes"
            ></predictions-sankey>
          </v-card-text>
        </v-card>

        <!-- Predictions Table -->
        <v-card v-if="resultsDB" class="mb-4">
          <v-card-title>Predictions</v-card-title>
          <v-card-text>
            <predictions-table
              :cell-names="resultsDB.cellNames"
              :predictions="resultsDB.predictions"
              :probabilities="resultsDB.probabilities"
              :cell-type-names="resultsDB.cellTypeNames"
              :coordinates="resultsDB.coords"
            ></predictions-table>
          </v-card-text>
        </v-card>
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup lang="ts">
import { useTheme } from 'vuetify'
import { ref, onMounted, onUnmounted } from 'vue'

import { openDB } from 'idb'
import SIMSWorker from './workers/sims-worker.ts?worker'

import PredictionsTable from './PredictionsTable.vue'
import PredictionsPlot from './PredictionsPlot.vue'
import PredictionsSankey from './PredictionsSankey.vue'

const theme = useTheme()
const isProcessing = ref(false)
const currentStatus = ref('')
const processingProgress = ref(0)
const processingTime = ref(0)
const processingStartTime = ref(0)

// Model metadata type
interface ModelMetadata {
  title: string
  submitter: string
  [key: string]: unknown
}

// TypeScript interface for dataset
interface Dataset {
  datasetLabel: string
  cellNames: string[]
  cellTypes: number[]
  cellTypeNames: string[]
  predictions: number[][]
  probabilities: Float32Array[]
  coords: number[]
  genes: string[]
  overallTopGenes: number[]
  topGeneIndicesByClass: number[][]
}

// Available files and workers
const predictWorkerOptions = ref<{ title: string; value: string }[]>([])
const clusterWorkerOptions = ref(['UMAP', 'PUMAP', 'HDBSCAN'])

// Selected options
const selectedFile = ref<File | null>(null)
const selectedPredictWorker = ref('default')
const selectedClusterWorker = ref('UMAP')

// Model metadata
const modelMetadata = ref<Record<string, ModelMetadata>>({})

// Fetch models and their metadata
async function fetchModels() {
  try {
    const modelsResponse = await fetch('/models/models.txt')
    const modelsText = await modelsResponse.text()
    const modelIds = modelsText.trim().split('\n')

    // Fetch metadata for each model
    const metadata: Record<string, ModelMetadata> = {}
    for (const modelId of modelIds) {
      const metadataResponse = await fetch(`/models/${modelId}.json`)
      metadata[modelId] = await metadataResponse.json()
    }

    modelMetadata.value = metadata
    predictWorkerOptions.value = modelIds.map((id) => ({
      title: metadata[id].title || id,
      value: id,
    }))
  } catch (error) {
    console.error('Error fetching models:', error)
    currentStatus.value = 'Error loading models'
  }
}

// Workers
const predictWorker = ref<Worker | null>(null)
const processingWorker = ref<Worker | null>(null)
const clusterWorker = ref<Worker | null>(null)

// Results
const analysisResults = ref<
  Array<{
    type: string
    summary: string
    detailedResult?: Float32Array
    min?: Float32Array
    max?: Float32Array
  }>
>([])

function toggleTheme() {
  theme.global.name.value = theme.global.current.value.dark ? 'light' : 'dark'
}

// IndexedDB
const DB_VERSION = 2

const resultsDB = ref<Dataset | null>(null)

async function loadDataset() {
  try {
    const db = await openDB('sims-web', DB_VERSION, {
      upgrade(db, oldVersion, _newVersion, transaction) {
        // Case 1: No database - create it
        if (!db.objectStoreNames.contains('datasets')) {
          db.createObjectStore('datasets', {
            keyPath: 'datasetLabel',
            autoIncrement: true,
          })
        }

        // Case 2: Version 1 exists - clear it
        if (oldVersion === 1) {
          transaction.objectStore('datasets').clear()
          currentStatus.value = 'Database upgraded - previous results cleared'
        }
      },
    })

    // Case 3: Version 2 exists - load first dataset
    const keys = await db.getAllKeys('datasets')
    if (keys.length > 0) {
      resultsDB.value = await db.get('datasets', keys[0])
    }

    db.close()
  } catch (error) {
    console.error('Database error:', error)
    currentStatus.value = 'Error accessing database'
  }
}

function initializeWorkers() {
  // Create file worker
  predictWorker.value = new SIMSWorker()
  predictWorker.value.onmessage = handlePredictWorkerMessage

  // Create processing worker
  // processingWorker.value = new Worker(new URL('./workers/processingWorker.js', import.meta.url))
  // processingWorker.value.onmessage = handleProcessingWorkerMessage
}

function runPipeline() {
  // Check if a file is selected
  if (!selectedFile.value) {
    currentStatus.value = 'Please select an H5AD file first'
    return
  }

  // Reset previous results
  analysisResults.value = []
  isProcessing.value = true
  currentStatus.value = 'Starting pipeline...'
  processingProgress.value = 0
  processingStartTime.value = Date.now()

  // Initialize workers if needed
  if (!predictWorker.value || !processingWorker.value) {
    initializeWorkers()
  }

  // Create selected analysis worker based on selection
  if (clusterWorker.value) {
    clusterWorker.value.terminate()
  }

  // if (selectedClusterWorker.value === 'Average Calculator') {
  //   clusterWorker.value = new Worker(new URL('./workers/averageWorker.js', import.meta.url))
  //   clusterWorker.value.onmessage = handleClusterWorkerMessage
  // } else {
  //   clusterWorker.value = new Worker(new URL('./workers/minMaxWorker.js', import.meta.url))
  //   clusterWorker.value.onmessage = handleClusterWorkerMessage
  // }

  // Start the pipeline by sending a message to the file worker
  const modelURL = `${window.location.protocol}//${window.location.host}/models`
  predictWorker.value?.postMessage({
    type: 'startPrediction',
    modelID: selectedPredictWorker.value,
    modelURL: modelURL,
    h5File: selectedFile.value,
    cellRangePercent: 25,
  })
}

function handleStop() {
  // Terminate workers
  predictWorker.value?.terminate()
  processingWorker.value?.terminate()
  clusterWorker.value?.terminate()
  // Reinitialize workers
  initializeWorkers()
  isProcessing.value = false
}

function handleFileSelected(files: File | File[]) {
  const file = Array.isArray(files) ? files[0] : files
  if (file) {
    selectedFile.value = file
  } else {
    selectedFile.value = null
  }
}

function handlePredictWorkerMessage(event: MessageEvent) {
  const { type, message } = event.data

  if (type === 'status') {
    currentStatus.value = message
  } else if (type === 'batchData') {
    // Pass the batch data to the processing worker
    processingWorker.value?.postMessage({
      type: 'processBatch',
      batch: event.data.batch,
      batchSize: event.data.batchSize,
      numCells: event.data.numCells,
      numGenes: event.data.numGenes,
    })
    currentStatus.value = message
  } else if (type === 'processingProgress') {
    // Update progress based on countFinished and totalToProcess
    const { countFinished, totalToProcess } = event.data
    processingProgress.value = (countFinished / totalToProcess) * 100
    currentStatus.value = `Processing: ${countFinished} of ${totalToProcess} complete (${Math.round(processingProgress.value)}%)`
  } else if (type === 'finishedPrediction') {
    // Calculate processing time
    processingTime.value = (Date.now() - processingStartTime.value) / 1000

    // Reset UI state
    isProcessing.value = false
    processingProgress.value = 0
    currentStatus.value = ''

    // Add processing result to analysis results
    analysisResults.value.push({
      type: 'Prediction',
      summary: `Processed ${event.data.totalProcessed} items in ${processingTime.value.toFixed(2)} seconds`,
    })
    loadDataset()
  } else if (type === 'predictionError') {
    currentStatus.value = message
    isProcessing.value = false
  }
}

// function handleProcessingWorkerMessage(event: MessageEvent) {
//   const { type, message } = event.data

//   if (type === 'status') {
//     currentStatus.value = message
//   } else if (type === 'batchProcessed') {
//     // Pass the processed data to the selected analysis worker
//     if (selectedClusterWorker.value === 'Average Calculator') {
//       clusterWorker.value?.postMessage({
//         type: 'computeAverage',
//         batch: event.data.batch,
//         batchSize: event.data.batchSize,
//         numCells: event.data.numCells,
//         numGenes: event.data.numGenes,
//       })
//     } else {
//       clusterWorker.value?.postMessage({
//         type: 'computeMinMax',
//         batch: event.data.batch,
//         batchSize: event.data.batchSize,
//         numCells: event.data.numCells,
//         numGenes: event.data.numGenes,
//       })
//     }
//     currentStatus.value = message
//   } else if (type === 'error') {
//     currentStatus.value = message
//     isProcessing.value = false
//   }
// }

// function handleClusterWorkerMessage(event: MessageEvent) {
//   const { type, message } = event.data

//   if (type === 'status') {
//     currentStatus.value = message
//   } else if (type === 'analysisResult') {
//     analysisResults.value.push(event.data.result)
//     currentStatus.value = message
//     isProcessing.value = false
//   } else if (type === 'error') {
//     currentStatus.value = message
//     isProcessing.value = false
//   }
// }

// Fetch a sample file on application load
async function fetchSampleFile() {
  try {
    const sampleFileName = 'sample.h5ad'
    currentStatus.value = 'Loading sample file...'

    const response = await fetch(sampleFileName)
    const blob = await response.blob()
    const file = new File([blob], sampleFileName, { type: blob.type })

    selectedFile.value = file
    currentStatus.value = 'Sample file loaded'
    console.log('Sample File:', file)
  } catch (error) {
    console.error('Error loading sample file:', error)
    currentStatus.value = 'Error loading sample file'
  }
}

onMounted(() => {
  loadDataset()
  initializeWorkers()
  fetchModels()
  fetchSampleFile() // Load the sample file when the app mounts
})

onUnmounted(() => {
  // Clean up workers
  predictWorker.value?.terminate()
  processingWorker.value?.terminate()
  clusterWorker.value?.terminate()
})
</script>

<style></style>
