// src/PredictionsTable.jsx
import PropTypes from "prop-types";
import Box from "@mui/material/Box";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import DownloadIcon from "@mui/icons-material/Download";

export const PredictionsTable = ({
  cellNames,
  predictions,
  probabilities,
  cellTypeNames,
  coordinates,
}) => {
  function downloadCSV() {
    let csvContent =
      "cell_id,pred_0,pred_1,pred_2,prob_0,prob_1,prob_2,umap_0,umap_1\n";

    cellNames.forEach((cellName, cellIndex) => {
      let cellResults = "";
      for (let i = 0; i < 3; i++) {
        cellResults += `,${cellTypeNames[predictions[cellIndex][i]]}`;
      }
      for (let i = 0; i < 3; i++) {
        cellResults += `,${probabilities[cellIndex][i].toFixed(4)}`;
      }
      if (cellIndex < coordinates.length / 2) {
        cellResults += `,${coordinates[2 * cellIndex].toFixed(4)},${coordinates[
          2 * cellIndex + 1
        ].toFixed(4)}`;
      } else {
        // If there are no UMAP coordinates, just add a comma
        cellResults += ",,";
      }
      csvContent += `${cellName}${cellResults}\n`;
    });

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const downloadLink = document.createElement("a");
    const url = URL.createObjectURL(blob);
    downloadLink.setAttribute("href", url);
    downloadLink.setAttribute("download", "predictions.csv");
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
  }

  return (
    <TableContainer>
      <Box mt={2}>
        <Typography>First 100 predictions:</Typography>
        <IconButton
          onClick={() => downloadCSV(predictions)}
          disabled={predictions === null}
          color="primary"
          style={{ float: "right" }}
        >
          <DownloadIcon />
        </IconButton>
      </Box>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>Cell</TableCell>
            <TableCell>Class 1</TableCell>
            <TableCell>Prob 1</TableCell>
            <TableCell>Class 2</TableCell>
            <TableCell>Prob 2</TableCell>
            <TableCell>Class 3</TableCell>
            <TableCell>Prob 3</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {cellNames.slice(0, 100).map((cellName, cellIndex) => (
            <TableRow
              key={cellName}
              sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
            >
              <TableCell component="th" scope="row">
                {cellName}
              </TableCell>
              <TableCell>{cellTypeNames[predictions[cellIndex][0]]}</TableCell>
              <TableCell>{probabilities[cellIndex][0].toFixed(4)}</TableCell>
              <TableCell>{cellTypeNames[predictions[cellIndex][1]]}</TableCell>
              <TableCell>{probabilities[cellIndex][1].toFixed(4)}</TableCell>
              <TableCell>{cellTypeNames[predictions[cellIndex][2]]}</TableCell>
              <TableCell>{probabilities[cellIndex][2].toFixed(4)}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};

PredictionsTable.propTypes = {
  cellNames: PropTypes.arrayOf(PropTypes.string),
  predictions: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.number)),
  probabilities: PropTypes.arrayOf(PropTypes.instanceOf(Float32Array)),
  cellTypeNames: PropTypes.arrayOf(PropTypes.string),
  coordinates: PropTypes.arrayOf(PropTypes.number),
};

// src/PredictionsTable.vue
<template>
  <div>
    <div class="mt-2">
      <p>First 100 predictions:</p>
      <v-btn
        icon
        @click="downloadCSV"
        :disabled="!predictions"
        color="primary"
        style="float: right"
      >
        <v-icon>mdi-download</v-icon>
      </v-btn>
    </div>
    <v-table>
      <thead>
        <tr>
          <th>Cell</th>
          <th>Class 1</th>
          <th>Prob 1</th>
          <th>Class 2</th>
          <th>Prob 2</th>
          <th>Class 3</th>
          <th>Prob 3</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(cellName, cellIndex) in cellNames.slice(0, 100)" :key="cellName">
          <td>{{ cellName }}</td>
          <td>{{ cellTypeNames[predictions[cellIndex][0]] }}</td>
          <td>{{ probabilities[cellIndex][0].toFixed(4) }}</td>
          <td>{{ cellTypeNames[predictions[cellIndex][1]] }}</td>
          <td>{{ probabilities[cellIndex][1].toFixed(4) }}</td>
          <td>{{ cellTypeNames[predictions[cellIndex][2]] }}</td>
          <td>{{ probabilities[cellIndex][2].toFixed(4) }}</td>
        </tr>
      </tbody>
    </v-table>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';

export default defineComponent({
  name: 'PredictionsTable',
  props: {
    cellNames: {
      type: Array as PropType<string[]>,
      required: true
    },
    predictions: {
      type: Array as PropType<number[][]>,
      required: true
    },
    probabilities: {
      type: Array as PropType<Float32Array[]>,
      required: true
    },
    cellTypeNames: {
      type: Array as PropType<string[]>,
      required: true
    },
    coordinates: {
      type: Array as PropType<number[]>,
      required: true
    }
  },
  setup(props) {
    const downloadCSV = () => {
      let csvContent =
        "cell_id,pred_0,pred_1,pred_2,prob_0,prob_1,prob_2,umap_0,umap_1\n";

      props.cellNames.forEach((cellName, cellIndex) => {
        let cellResults = "";
        for (let i = 0; i < 3; i++) {
          cellResults += `,${props.cellTypeNames[props.predictions[cellIndex][i]]}`;
        }
        for (let i = 0; i < 3; i++) {
          cellResults += `,${props.probabilities[cellIndex][i].toFixed(4)}`;
        }
        if (cellIndex < props.coordinates.length / 2) {
          cellResults += `,${props.coordinates[2 * cellIndex].toFixed(4)},${props.coordinates[
            2 * cellIndex + 1
          ].toFixed(4)}`;
        } else {
          // If there are no UMAP coordinates, just add a comma
          cellResults += ",,";
        }
        csvContent += `${cellName}${cellResults}\n`;
      });

      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const downloadLink = document.createElement("a");
      const url = URL.createObjectURL(blob);
      downloadLink.setAttribute("href", url);
      downloadLink.setAttribute("download", "predictions.csv");
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
    };

    return {
      downloadCSV
    };
  }
});
</script>

<style scoped>
/* Component-specific styles if needed */
</style>
